<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $operation_id bigint(20,0) unsigned NOT NULL
 * @property mixed $developer_id bigint(20,0) unsigned NOT NULL
 * @property mixed $simulator_id bigint(20,0) unsigned NOT NULL
 * @property mixed $name varchar(75) NOT NULL
 * @property mixed $icao varchar(6)
 * @property mixed $description mediumtext(16777215)
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @property null|false|\LiveryManager\DB\Operation\OperationRecord $operation
 * @property null|false|\LiveryManager\DB\Developer\DeveloperRecord $developer
 * @property null|false|\LiveryManager\DB\Simulator\SimulatorRecord $simulator
 */
trait AirframeFields
{
}
