<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe;

use Atlas\Table\Table;

/**
 * @method AirframeRow|null fetchRow($primaryVal)
 * @method AirframeRow[] fetchRows(array $primaryVals)
 * @method AirframeTableSelect select(array $whereEquals = [])
 * @method AirframeRow newRow(array $cols = [])
 * @method AirframeRow newSelectedRow(array $cols)
 */
class AirframeTable extends Table
{
    public const DRIVER = 'mysql';

    public const NAME = 'airframe';

    public const COLUMNS = [
        'id' => array(
  'name' => 'id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => true,
  'primary' => true,
  'options' => null,
),
        'operation_id' => array(
  'name' => 'operation_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'developer_id' => array(
  'name' => 'developer_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'simulator_id' => array(
  'name' => 'simulator_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'name' => array(
  'name' => 'name',
  'type' => 'varchar',
  'size' => 75,
  'scale' => null,
  'notnull' => true,
  'default' => '\'\'',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'icao' => array(
  'name' => 'icao',
  'type' => 'varchar',
  'size' => 6,
  'scale' => null,
  'notnull' => false,
  'default' => 'NULL',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'description' => array(
  'name' => 'description',
  'type' => 'mediumtext',
  'size' => 16777215,
  'scale' => null,
  'notnull' => false,
  'default' => 'NULL',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'enabled' => array(
  'name' => 'enabled',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => 1,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'created_at' => array(
  'name' => 'created_at',
  'type' => 'datetime',
  'size' => null,
  'scale' => null,
  'notnull' => true,
  'default' => 'current_timestamp()',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
    ];

    public const COLUMN_NAMES = [
        'id',
        'operation_id',
        'developer_id',
        'simulator_id',
        'name',
        'icao',
        'description',
        'enabled',
        'created_at',
    ];

    public const COLUMN_DEFAULTS = [
        'id' => null,
        'operation_id' => null,
        'developer_id' => null,
        'simulator_id' => null,
        'name' => '\'\'',
        'icao' => 'NULL',
        'description' => 'NULL',
        'enabled' => 1,
        'created_at' => 'current_timestamp()',
    ];

    public const PRIMARY_KEY = [
        'id',
    ];

    public const AUTOINC_COLUMN = 'id';

    public const AUTOINC_SEQUENCE = null;
}
