<?php
/*
 * Copyright (c) 2023 VWX Systems
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $operation_id int(10,0) unsigned NOT NULL
 * @property mixed $developer_id int(10,0) unsigned NOT NULL
 * @property mixed $simulator_id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(75) NOT NULL
 * @property mixed $icao varchar(6)
 * @property mixed $description mediumtext(16777215)
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @property null|false|\LiveryManager\DB\Operation\OperationRecord $operation
 * @property null|false|\LiveryManager\DB\Developer\DeveloperRecord $developer
 * @property null|false|\LiveryManager\DB\Simulator\SimulatorRecord $simulator
 */
trait AirframeFields
{
}
