<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryVersion;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $livery_id bigint(20,0) unsigned NOT NULL
 * @property mixed $version varchar(16) NOT NULL
 * @property mixed $changelog mediumtext(16777215)
 * @property mixed $file_name varchar(100) NOT NULL
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @property null|false|\LiveryManager\DB\Livery\LiveryRecord $livery
 */
trait LiveryVersionFields
{
}
