<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Developer;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $name varchar(50) NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @property null|\LiveryManager\DB\Airframe\AirframeRecordSet $airframes
 */
trait DeveloperFields
{
}
