<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Phinxlog\_generated;

use Atlas\Mapper\MapperEvents;

abstract class PhinxlogEvents_ extends MapperEvents
{
}
