<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Phinxlog\_generated;

use Atlas\Mapper\MapperSelect;
use LiveryManager\DB\Phinxlog\PhinxlogRecord;
use LiveryManager\DB\Phinxlog\PhinxlogRecordSet;

/**
 * @method ?PhinxlogRecord fetchRecord()
 * @method PhinxlogRecord[] fetchRecords()
 * @method PhinxlogRecordSet fetchRecordSet()
 * @method ?PhinxlogRow fetchRow()
 * @method PhinxlogRow[] fetchRows()
 */
abstract class PhinxlogSelect_ extends MapperSelect
{
}
