<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Phinxlog\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $version bigint(19,0) NOT NULL
 * @property mixed $migration_name varchar(100)
 * @property mixed $start_time timestamp
 * @property mixed $end_time timestamp
 * @property mixed $breakpoint tinyint(3,0) NOT NULL
 * @method \LiveryManager\DB\Phinxlog\PhinxlogRow getRow()
 */
abstract class PhinxlogRecord_ extends Record
{
}
