<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Phinxlog\_generated;

use Atlas\Mapper\Related;

abstract class PhinxlogRelated_ extends Related
{
}
