<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Phinxlog\_generated;

use Atlas\Table\TableSelect;
use LiveryManager\DB\Phinxlog\PhinxlogRow;

/**
 * @method ?PhinxlogRow fetchRow()
 * @method PhinxlogRow[] fetchRows()
 */
abstract class PhinxlogTableSelect_ extends TableSelect
{
}
