<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Phinxlog\_generated;

use Atlas\Table\Table;
use LiveryManager\DB\Phinxlog\PhinxlogRow;
use LiveryManager\DB\Phinxlog\PhinxlogTableSelect;

/**
 * @method ?PhinxlogRow fetchRow(mixed $primaryVal)
 * @method PhinxlogRow[] fetchRows(array $primaryVals)
 * @method PhinxlogTableSelect select(array $whereEquals = [])
 * @method PhinxlogRow newRow(array $cols = [])
 * @method PhinxlogRow newSelectedRow(array $cols)
 */
abstract class PhinxlogTable_ extends Table
{
    public const DRIVER = 'mysql';

    public const NAME = 'phinxlog';

    public const COLUMNS = [
  'version' => 
  [
    'name' => 'version',
    'type' => 'bigint',
    'size' => 19,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => true,
    'options' => NULL,
  ),
  'migration_name' => 
  [
    'name' => 'migration_name',
    'type' => 'varchar',
    'size' => 100,
    'scale' => NULL,
    'notnull' => false,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'start_time' => 
  [
    'name' => 'start_time',
    'type' => 'timestamp',
    'size' => NULL,
    'scale' => NULL,
    'notnull' => false,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'end_time' => 
  [
    'name' => 'end_time',
    'type' => 'timestamp',
    'size' => NULL,
    'scale' => NULL,
    'notnull' => false,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'breakpoint' => 
  [
    'name' => 'breakpoint',
    'type' => 'tinyint',
    'size' => 3,
    'scale' => 0,
    'notnull' => true,
    'default' => 0,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
);

    public const COLUMN_NAMES = [
        'version',
        'migration_name',
        'start_time',
        'end_time',
        'breakpoint',
    ];

    public const PRIMARY_KEY = [
        'version',
    ];

    public const COMPOSITE_KEY = false;

    public const AUTOINC_COLUMN = null;

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = PhinxlogRow::CLASS;
}
