<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Simulator\_generated;

use Atlas\Table\TableSelect;
use LiveryManager\DB\Simulator\SimulatorRow;

/**
 * @method ?SimulatorRow fetchRow()
 * @method SimulatorRow[] fetchRows()
 */
abstract class SimulatorTableSelect_ extends TableSelect
{
}
