<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Simulator\_generated;

use Atlas\Mapper\MapperSelect;
use LiveryManager\DB\Simulator\SimulatorRecord;
use LiveryManager\DB\Simulator\SimulatorRecordSet;

/**
 * @method ?SimulatorRecord fetchRecord()
 * @method SimulatorRecord[] fetchRecords()
 * @method SimulatorRecordSet fetchRecordSet()
 * @method ?SimulatorRow fetchRow()
 * @method SimulatorRow[] fetchRows()
 */
abstract class SimulatorSelect_ extends MapperSelect
{
}
