<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Simulator\_generated;

use Atlas\Mapper\RecordSet;
use LiveryManager\DB\Simulator\SimulatorRecord;
use LiveryManager\DB\Simulator\SimulatorRecordSet;

/**
 * @method __construct(SimulatorRecord[], callable $newRecordFactory)
 * @method SimulatorRecord offsetGet($offset)
 * @method SimulatorRecord appendNew(array $fields = [])
 * @method ?SimulatorRecord getOneBy(array $whereEquals)
 * @method SimulatorRecordSet getAllBy(array $whereEquals)
 * @method ?SimulatorRecord detachOneBy(array $whereEquals)
 * @method SimulatorRecordSet detachAllBy(array $whereEquals)
 * @method SimulatorRecordSet detachAll()
 * @method SimulatorRecordSet detachDeleted()
 */
abstract class SimulatorRecordSet_ extends RecordSet
{
}
