<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Simulator\_generated;

use Atlas\Mapper\Mapper;
use LiveryManager\DB\Simulator\SimulatorRecord;
use LiveryManager\DB\Simulator\SimulatorRecordSet;
use LiveryManager\DB\Simulator\SimulatorRelated;
use LiveryManager\DB\Simulator\SimulatorSelect;
use LiveryManager\DB\Simulator\SimulatorTable;

/**
 * @method SimulatorTable getTable()
 * @method ?SimulatorRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?SimulatorRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method SimulatorRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method SimulatorRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method SimulatorRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method SimulatorRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method SimulatorSelect select(array $whereEquals = [])
 * @method SimulatorRecord newRecord(array $fields = [])
 * @method SimulatorRecord[] newRecords(array $fieldSets)
 * @method SimulatorRecordSet newRecordSet(SimulatorRecord[] $records = [])
 * @method SimulatorRecord turnRowIntoRecord(SimulatorRow $row, array $loadRelated = [])
 * @method SimulatorRecord[] turnRowsIntoRecords(SimulatorRow[] $rows, array $loadRelated = [])
 */
abstract class Simulator_ extends Mapper
{
    public const RECORD_CLASS = SimulatorRecord::CLASS;
    public const RECORD_SET_CLASS = SimulatorRecordSet::CLASS;
    public const RELATED_CLASS = SimulatorRelated::CLASS;
    public const SELECT_CLASS = SimulatorSelect::CLASS;
}
