<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Simulator\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(50) NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @method \LiveryManager\DB\Simulator\SimulatorRow getRow()
 */
abstract class SimulatorRecord_ extends Record
{
}
