<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryType;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $name varchar(50) NOT NULL
 * @property mixed $description mediumtext(16777215)
 * @property mixed $created_at datetime NOT NULL
 * @property null|\LiveryManager\DB\Livery\LiveryRecordSet $liveries
 */
trait LiveryTypeFields
{
}
