<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $airframe_id int(10,0) unsigned NOT NULL
 * @property mixed $livery_type_id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(75)
 * @property mixed $tailno varchar(20)
 * @property mixed $storage_path varchar(75) NOT NULL
 * @property mixed $description mediumtext(16777215)
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 */
class LiveryRow extends Row
{
    protected $cols = [
        'id' => null,
        'airframe_id' => null,
        'livery_type_id' => null,
        'name' => '\'\'',
        'tailno' => '\'\'',
        'storage_path' => '\'/unassigned\'',
        'description' => 'NULL',
        'enabled' => 1,
        'created_at' => 'current_timestamp()',
    ];
}
