<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery;

use Atlas\Table\Table;

/**
 * @method LiveryRow|null fetchRow($primaryVal)
 * @method LiveryRow[] fetchRows(array $primaryVals)
 * @method LiveryTableSelect select(array $whereEquals = [])
 * @method LiveryRow newRow(array $cols = [])
 * @method LiveryRow newSelectedRow(array $cols)
 */
class LiveryTable extends Table
{
    public const DRIVER = 'mysql';

    public const NAME = 'livery';

    public const COLUMNS = [
        'id' => array(
  'name' => 'id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => true,
  'primary' => true,
  'options' => null,
),
        'airframe_id' => array(
  'name' => 'airframe_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'livery_type_id' => array(
  'name' => 'livery_type_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'name' => array(
  'name' => 'name',
  'type' => 'varchar',
  'size' => 75,
  'scale' => null,
  'notnull' => false,
  'default' => '\'\'',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'tailno' => array(
  'name' => 'tailno',
  'type' => 'varchar',
  'size' => 20,
  'scale' => null,
  'notnull' => false,
  'default' => '\'\'',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'storage_path' => array(
  'name' => 'storage_path',
  'type' => 'varchar',
  'size' => 75,
  'scale' => null,
  'notnull' => true,
  'default' => '\'/unassigned\'',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'description' => array(
  'name' => 'description',
  'type' => 'mediumtext',
  'size' => 16777215,
  'scale' => null,
  'notnull' => false,
  'default' => 'NULL',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'enabled' => array(
  'name' => 'enabled',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => 1,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'created_at' => array(
  'name' => 'created_at',
  'type' => 'datetime',
  'size' => null,
  'scale' => null,
  'notnull' => true,
  'default' => 'current_timestamp()',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
    ];

    public const COLUMN_NAMES = [
        'id',
        'airframe_id',
        'livery_type_id',
        'name',
        'tailno',
        'storage_path',
        'description',
        'enabled',
        'created_at',
    ];

    public const COLUMN_DEFAULTS = [
        'id' => null,
        'airframe_id' => null,
        'livery_type_id' => null,
        'name' => '\'\'',
        'tailno' => '\'\'',
        'storage_path' => '\'/unassigned\'',
        'description' => 'NULL',
        'enabled' => 1,
        'created_at' => 'current_timestamp()',
    ];

    public const PRIMARY_KEY = [
        'id',
    ];

    public const AUTOINC_COLUMN = 'id';

    public const AUTOINC_SEQUENCE = null;
}
