<?php
/*
 * Copyright (c) 2023 VWX Systems
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery;

use Atlas\Table\Table;

/**
 * @method LiveryRow|null fetchRow($primaryVal)
 * @method LiveryRow[] fetchRows(array $primaryVals)
 * @method LiveryTableSelect select(array $whereEquals = [])
 * @method LiveryRow newRow(array $cols = [])
 * @method LiveryRow newSelectedRow(array $cols)
 */
class LiveryTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'livery';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'airframe_id' => array (
  'name' => 'airframe_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'livery_type_id' => array (
  'name' => 'livery_type_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'name' => array (
  'name' => 'name',
  'type' => 'varchar',
  'size' => 75,
  'scale' => NULL,
  'notnull' => false,
  'default' => '\'\'',
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'tailno' => array (
  'name' => 'tailno',
  'type' => 'varchar',
  'size' => 20,
  'scale' => NULL,
  'notnull' => false,
  'default' => '\'\'',
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'storage_path' => array (
  'name' => 'storage_path',
  'type' => 'varchar',
  'size' => 75,
  'scale' => NULL,
  'notnull' => true,
  'default' => '\'/unassigned\'',
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'description' => array (
  'name' => 'description',
  'type' => 'mediumtext',
  'size' => 16777215,
  'scale' => NULL,
  'notnull' => false,
  'default' => 'NULL',
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'enabled' => array (
  'name' => 'enabled',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => 1,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'created_at' => array (
  'name' => 'created_at',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => 'current_timestamp()',
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'airframe_id',
        'livery_type_id',
        'name',
        'tailno',
        'storage_path',
        'description',
        'enabled',
        'created_at',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'airframe_id' => null,
        'livery_type_id' => null,
        'name' => '\'\'',
        'tailno' => '\'\'',
        'storage_path' => '\'/unassigned\'',
        'description' => 'NULL',
        'enabled' => 1,
        'created_at' => 'current_timestamp()',
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
