<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $airframe_id int(10,0) unsigned NOT NULL
 * @property mixed $livery_type_id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(75)
 * @property mixed $tailno varchar(20)
 * @property mixed $storage_path varchar(75) NOT NULL
 * @property mixed $description mediumtext(16777215)
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @property null|false|\LiveryManager\DB\Airframe\AirframeRecord $airframe
 * @property null|false|\LiveryManager\DB\LiveryType\LiveryTypeRecord $livery_type
 * @property null|\LiveryManager\DB\LiveryVersion\LiveryVersionRecordSet $versions
 */
trait LiveryFields
{
}
