<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(75)
 * @property mixed $tailno varchar(20)
 * @property mixed $storage_path varchar(75) NOT NULL
 * @property mixed $airframe_id int(10,0) unsigned NOT NULL
 * @property mixed $livery_type_id int(10,0) unsigned NOT NULL
 * @property mixed $developer_id int(10,0) unsigned NOT NULL
 * @property mixed $simulator_id int(10,0) unsigned NOT NULL
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 */
trait LiveryFields
{
}
