<?php

return array (
  'database' => 
  array (
    'default_character_set_name' => 'utf8mb4',
    'default_collation_name' => 'utf8mb4_general_ci',
  ),
  'tables' => 
  array (
    'livery' => 
    array (
      'table' => 
      array (
        'table_name' => 'livery',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'airframe_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'airframe_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'livery_type_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'livery_type_id',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'name',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => '\'\'',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 75,
          'CHARACTER_OCTET_LENGTH' => 300,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(75)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'tailno' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'tailno',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => '\'\'',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 20,
          'CHARACTER_OCTET_LENGTH' => 80,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(20)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'storage_path' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'storage_path',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => '\'/unassigned\'',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 75,
          'CHARACTER_OCTET_LENGTH' => 300,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(75)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'description' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'description',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'mediumtext',
          'CHARACTER_MAXIMUM_LENGTH' => 16777215,
          'CHARACTER_OCTET_LENGTH' => 16777215,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'mediumtext',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'enabled' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'enabled',
          'ORDINAL_POSITION' => 8,
          'COLUMN_DEFAULT' => '1',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 3,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(3) unsigned',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 9,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'livery',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'fk_livery_type_airframe' => 
        array (
          1 => 
          array (
            'Table' => 'livery',
            'Non_unique' => 1,
            'Key_name' => 'fk_livery_type_airframe',
            'Seq_in_index' => 1,
            'Column_name' => 'livery_type_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'fk_livery_airframe' => 
        array (
          1 => 
          array (
            'Table' => 'livery',
            'Non_unique' => 1,
            'Key_name' => 'fk_livery_airframe',
            'Seq_in_index' => 1,
            'Column_name' => 'airframe_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        'fk_livery_airframe' => 
        array (
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'airframe_id',
          'CONSTRAINT_NAME' => 'fk_livery_airframe',
          'REFERENCED_TABLE_NAME' => 'airframe',
          'REFERENCED_COLUMN_NAME' => 'id',
          'UPDATE_RULE' => 'RESTRICT',
          'DELETE_RULE' => 'RESTRICT',
        ),
        'fk_livery_type_airframe' => 
        array (
          'TABLE_NAME' => 'livery',
          'COLUMN_NAME' => 'livery_type_id',
          'CONSTRAINT_NAME' => 'fk_livery_type_airframe',
          'REFERENCED_TABLE_NAME' => 'livery_type',
          'REFERENCED_COLUMN_NAME' => 'id',
          'UPDATE_RULE' => 'RESTRICT',
          'DELETE_RULE' => 'RESTRICT',
        ),
      ),
    ),
    'operation' => 
    array (
      'table' => 
      array (
        'table_name' => 'operation',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'operation',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'operation',
          'COLUMN_NAME' => 'name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => '\'\'',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 50,
          'CHARACTER_OCTET_LENGTH' => 200,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(50)',
          'COLUMN_KEY' => 'UNI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'operation',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'operation',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'name' => 
        array (
          1 => 
          array (
            'Table' => 'operation',
            'Non_unique' => 0,
            'Key_name' => 'name',
            'Seq_in_index' => 1,
            'Column_name' => 'name',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'developer' => 
    array (
      'table' => 
      array (
        'table_name' => 'developer',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'developer',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'developer',
          'COLUMN_NAME' => 'name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => '\'\'',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 50,
          'CHARACTER_OCTET_LENGTH' => 200,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(50)',
          'COLUMN_KEY' => 'UNI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'developer',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'developer',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'name' => 
        array (
          1 => 
          array (
            'Table' => 'developer',
            'Non_unique' => 0,
            'Key_name' => 'name',
            'Seq_in_index' => 1,
            'Column_name' => 'name',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'simulator' => 
    array (
      'table' => 
      array (
        'table_name' => 'simulator',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'simulator',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'simulator',
          'COLUMN_NAME' => 'name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => '\'\'',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 50,
          'CHARACTER_OCTET_LENGTH' => 200,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(50)',
          'COLUMN_KEY' => 'UNI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'simulator',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'simulator',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'name' => 
        array (
          1 => 
          array (
            'Table' => 'simulator',
            'Non_unique' => 0,
            'Key_name' => 'name',
            'Seq_in_index' => 1,
            'Column_name' => 'name',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'livery_type' => 
    array (
      'table' => 
      array (
        'table_name' => 'livery_type',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_type',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_type',
          'COLUMN_NAME' => 'name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => '\'\'',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 50,
          'CHARACTER_OCTET_LENGTH' => 200,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(50)',
          'COLUMN_KEY' => 'UNI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'description' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_type',
          'COLUMN_NAME' => 'description',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'mediumtext',
          'CHARACTER_MAXIMUM_LENGTH' => 16777215,
          'CHARACTER_OCTET_LENGTH' => 16777215,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'mediumtext',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_type',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'livery_type',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'name' => 
        array (
          1 => 
          array (
            'Table' => 'livery_type',
            'Non_unique' => 0,
            'Key_name' => 'name',
            'Seq_in_index' => 1,
            'Column_name' => 'name',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'livery_version' => 
    array (
      'table' => 
      array (
        'table_name' => 'livery_version',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_version',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'livery_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_version',
          'COLUMN_NAME' => 'livery_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'version' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_version',
          'COLUMN_NAME' => 'version',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'changelog' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_version',
          'COLUMN_NAME' => 'changelog',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'mediumtext',
          'CHARACTER_MAXIMUM_LENGTH' => 16777215,
          'CHARACTER_OCTET_LENGTH' => 16777215,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'mediumtext',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'file_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_version',
          'COLUMN_NAME' => 'file_name',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => '\'\'',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => 'UNI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'enabled' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_version',
          'COLUMN_NAME' => 'enabled',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => '1',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 3,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(3) unsigned',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'livery_version',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'livery_version',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'file_name' => 
        array (
          1 => 
          array (
            'Table' => 'livery_version',
            'Non_unique' => 0,
            'Key_name' => 'file_name',
            'Seq_in_index' => 1,
            'Column_name' => 'file_name',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'fk_livery_version_livery' => 
        array (
          1 => 
          array (
            'Table' => 'livery_version',
            'Non_unique' => 1,
            'Key_name' => 'fk_livery_version_livery',
            'Seq_in_index' => 1,
            'Column_name' => 'livery_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        'fk_livery_version_livery' => 
        array (
          'TABLE_NAME' => 'livery_version',
          'COLUMN_NAME' => 'livery_id',
          'CONSTRAINT_NAME' => 'fk_livery_version_livery',
          'REFERENCED_TABLE_NAME' => 'livery',
          'REFERENCED_COLUMN_NAME' => 'id',
          'UPDATE_RULE' => 'RESTRICT',
          'DELETE_RULE' => 'RESTRICT',
        ),
      ),
    ),
    'airframe' => 
    array (
      'table' => 
      array (
        'table_name' => 'airframe',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'operation_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'operation_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'developer_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'developer_id',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'simulator_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'simulator_id',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'name',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => '\'\'',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 75,
          'CHARACTER_OCTET_LENGTH' => 300,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(75)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'icao' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'icao',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 6,
          'CHARACTER_OCTET_LENGTH' => 24,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(6)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'description' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'description',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'mediumtext',
          'CHARACTER_MAXIMUM_LENGTH' => 16777215,
          'CHARACTER_OCTET_LENGTH' => 16777215,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'mediumtext',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'enabled' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'enabled',
          'ORDINAL_POSITION' => 8,
          'COLUMN_DEFAULT' => '1',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 3,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(3) unsigned',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 9,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'airframe',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'fk_airframe_operation' => 
        array (
          1 => 
          array (
            'Table' => 'airframe',
            'Non_unique' => 1,
            'Key_name' => 'fk_airframe_operation',
            'Seq_in_index' => 1,
            'Column_name' => 'operation_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'fk_airframe_developer' => 
        array (
          1 => 
          array (
            'Table' => 'airframe',
            'Non_unique' => 1,
            'Key_name' => 'fk_airframe_developer',
            'Seq_in_index' => 1,
            'Column_name' => 'developer_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'fk_airframe_simulator' => 
        array (
          1 => 
          array (
            'Table' => 'airframe',
            'Non_unique' => 1,
            'Key_name' => 'fk_airframe_simulator',
            'Seq_in_index' => 1,
            'Column_name' => 'simulator_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        'fk_airframe_developer' => 
        array (
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'developer_id',
          'CONSTRAINT_NAME' => 'fk_airframe_developer',
          'REFERENCED_TABLE_NAME' => 'developer',
          'REFERENCED_COLUMN_NAME' => 'id',
          'UPDATE_RULE' => 'RESTRICT',
          'DELETE_RULE' => 'RESTRICT',
        ),
        'fk_airframe_operation' => 
        array (
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'operation_id',
          'CONSTRAINT_NAME' => 'fk_airframe_operation',
          'REFERENCED_TABLE_NAME' => 'operation',
          'REFERENCED_COLUMN_NAME' => 'id',
          'UPDATE_RULE' => 'RESTRICT',
          'DELETE_RULE' => 'RESTRICT',
        ),
        'fk_airframe_simulator' => 
        array (
          'TABLE_NAME' => 'airframe',
          'COLUMN_NAME' => 'simulator_id',
          'CONSTRAINT_NAME' => 'fk_airframe_simulator',
          'REFERENCED_TABLE_NAME' => 'simulator',
          'REFERENCED_COLUMN_NAME' => 'id',
          'UPDATE_RULE' => 'RESTRICT',
          'DELETE_RULE' => 'RESTRICT',
        ),
      ),
    ),
    'phinxlog' => 
    array (
      'table' => 
      array (
        'table_name' => 'phinxlog',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_unicode_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'version' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'version',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'bigint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 19,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'bigint(20)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'migration_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'migration_name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'start_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'start_time',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'end_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'end_time',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'breakpoint' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'breakpoint',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 3,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(1)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'phinxlog',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'version',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
  ),
);