<?php
/*
 * Copyright (c) 2023 VWX Systems
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Simulator;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(50) NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @property null|\LiveryManager\DB\Airframe\AirframeRecordSet $airframes
 */
trait SimulatorFields
{
}
