<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Simulator;

use Atlas\Table\Table;

/**
 * @method SimulatorRow|null fetchRow($primaryVal)
 * @method SimulatorRow[] fetchRows(array $primaryVals)
 * @method SimulatorTableSelect select(array $whereEquals = [])
 * @method SimulatorRow newRow(array $cols = [])
 * @method SimulatorRow newSelectedRow(array $cols)
 */
class SimulatorTable extends Table
{
    public const DRIVER = 'mysql';

    public const NAME = 'simulator';

    public const COLUMNS = [
        'id' => array(
  'name' => 'id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => true,
  'primary' => true,
  'options' => null,
),
        'name' => array(
  'name' => 'name',
  'type' => 'varchar',
  'size' => 50,
  'scale' => null,
  'notnull' => true,
  'default' => '\'\'',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'created_at' => array(
  'name' => 'created_at',
  'type' => 'datetime',
  'size' => null,
  'scale' => null,
  'notnull' => true,
  'default' => 'current_timestamp()',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
    ];

    public const COLUMN_NAMES = [
        'id',
        'name',
        'created_at',
    ];

    public const COLUMN_DEFAULTS = [
        'id' => null,
        'name' => '\'\'',
        'created_at' => 'current_timestamp()',
    ];

    public const PRIMARY_KEY = [
        'id',
    ];

    public const AUTOINC_COLUMN = 'id';

    public const AUTOINC_SEQUENCE = null;
}
