<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe\_generated;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(75) NOT NULL
 * @property mixed $icao varchar(6)
 * @property mixed $operation_id int(10,0) unsigned NOT NULL
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 */
abstract class AirframeRow_ extends Row
{
    protected mixed $id = null;
    protected mixed $name = '';
    protected mixed $icao = null;
    protected mixed $operation_id = null;
    protected mixed $enabled = 1;
    protected mixed $created_at = 'current_timestamp()';
}
