<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe\_generated;

use Atlas\Mapper\RecordSet;
use LiveryManager\DB\Airframe\AirframeRecord;
use LiveryManager\DB\Airframe\AirframeRecordSet;

/**
 * @method __construct(AirframeRecord[], callable $newRecordFactory)
 * @method AirframeRecord offsetGet($offset)
 * @method AirframeRecord appendNew(array $fields = [])
 * @method ?AirframeRecord getOneBy(array $whereEquals)
 * @method AirframeRecordSet getAllBy(array $whereEquals)
 * @method ?AirframeRecord detachOneBy(array $whereEquals)
 * @method AirframeRecordSet detachAllBy(array $whereEquals)
 * @method AirframeRecordSet detachAll()
 * @method AirframeRecordSet detachDeleted()
 */
abstract class AirframeRecordSet_ extends RecordSet
{
}
