<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe\_generated;

use Atlas\Table\Table;
use LiveryManager\DB\Airframe\AirframeRow;
use LiveryManager\DB\Airframe\AirframeTableSelect;

/**
 * @method ?AirframeRow fetchRow(mixed $primaryVal)
 * @method AirframeRow[] fetchRows(array $primaryVals)
 * @method AirframeTableSelect select(array $whereEquals = [])
 * @method AirframeRow newRow(array $cols = [])
 * @method AirframeRow newSelectedRow(array $cols)
 */
abstract class AirframeTable_ extends Table
{
    public const DRIVER = 'mysql';

    public const NAME = 'airframe';

    public const COLUMNS = [
  'id' => 
  [
    'name' => 'id',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => true,
    'options' => NULL,
  ),
  'name' => 
  [
    'name' => 'name',
    'type' => 'varchar',
    'size' => 75,
    'scale' => NULL,
    'notnull' => true,
    'default' => '',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'icao' => 
  [
    'name' => 'icao',
    'type' => 'varchar',
    'size' => 6,
    'scale' => NULL,
    'notnull' => false,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'operation_id' => 
  [
    'name' => 'operation_id',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'enabled' => 
  [
    'name' => 'enabled',
    'type' => 'tinyint unsigned',
    'size' => 3,
    'scale' => 0,
    'notnull' => true,
    'default' => 1,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'created_at' => 
  [
    'name' => 'created_at',
    'type' => 'datetime',
    'size' => NULL,
    'scale' => NULL,
    'notnull' => true,
    'default' => 'current_timestamp()',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
);

    public const COLUMN_NAMES = [
        'id',
        'name',
        'icao',
        'operation_id',
        'enabled',
        'created_at',
    ];

    public const PRIMARY_KEY = [
        'id',
    ];

    public const COMPOSITE_KEY = false;

    public const AUTOINC_COLUMN = null;

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = AirframeRow::CLASS;
}
