<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(75) NOT NULL
 * @property mixed $icao varchar(6)
 * @property mixed $operation_id int(10,0) unsigned NOT NULL
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @method \LiveryManager\DB\Airframe\AirframeRow getRow()
 */
abstract class AirframeRecord_ extends Record
{
}
