<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe\_generated;

use Atlas\Mapper\Mapper;
use LiveryManager\DB\Airframe\AirframeRecord;
use LiveryManager\DB\Airframe\AirframeRecordSet;
use LiveryManager\DB\Airframe\AirframeRelated;
use LiveryManager\DB\Airframe\AirframeSelect;
use LiveryManager\DB\Airframe\AirframeTable;

/**
 * @method AirframeTable getTable()
 * @method ?AirframeRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?AirframeRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method AirframeRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method AirframeRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method AirframeRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method AirframeRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method AirframeSelect select(array $whereEquals = [])
 * @method AirframeRecord newRecord(array $fields = [])
 * @method AirframeRecord[] newRecords(array $fieldSets)
 * @method AirframeRecordSet newRecordSet(AirframeRecord[] $records = [])
 * @method AirframeRecord turnRowIntoRecord(AirframeRow $row, array $loadRelated = [])
 * @method AirframeRecord[] turnRowsIntoRecords(AirframeRow[] $rows, array $loadRelated = [])
 */
abstract class Airframe_ extends Mapper
{
    public const RECORD_CLASS = AirframeRecord::CLASS;
    public const RECORD_SET_CLASS = AirframeRecordSet::CLASS;
    public const RELATED_CLASS = AirframeRelated::CLASS;
    public const SELECT_CLASS = AirframeSelect::CLASS;
}
