<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe\_generated;

use Atlas\Table\TableSelect;
use LiveryManager\DB\Airframe\AirframeRow;

/**
 * @method ?AirframeRow fetchRow()
 * @method AirframeRow[] fetchRows()
 */
abstract class AirframeTableSelect_ extends TableSelect
{
}
