<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe\_generated;

use Atlas\Mapper\Related;

abstract class AirframeRelated_ extends Related
{
}
