<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Airframe\_generated;

use Atlas\Mapper\MapperSelect;
use LiveryManager\DB\Airframe\AirframeRecord;
use LiveryManager\DB\Airframe\AirframeRecordSet;

/**
 * @method ?AirframeRecord fetchRecord()
 * @method AirframeRecord[] fetchRecords()
 * @method AirframeRecordSet fetchRecordSet()
 * @method ?AirframeRow fetchRow()
 * @method AirframeRow[] fetchRows()
 */
abstract class AirframeSelect_ extends MapperSelect
{
}
