<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Developer\_generated;

use Atlas\Mapper\RecordSet;
use LiveryManager\DB\Developer\DeveloperRecord;
use LiveryManager\DB\Developer\DeveloperRecordSet;

/**
 * @method __construct(DeveloperRecord[], callable $newRecordFactory)
 * @method DeveloperRecord offsetGet($offset)
 * @method DeveloperRecord appendNew(array $fields = [])
 * @method ?DeveloperRecord getOneBy(array $whereEquals)
 * @method DeveloperRecordSet getAllBy(array $whereEquals)
 * @method ?DeveloperRecord detachOneBy(array $whereEquals)
 * @method DeveloperRecordSet detachAllBy(array $whereEquals)
 * @method DeveloperRecordSet detachAll()
 * @method DeveloperRecordSet detachDeleted()
 */
abstract class DeveloperRecordSet_ extends RecordSet
{
}
