<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Developer\_generated;

use Atlas\Table\TableEvents;

abstract class DeveloperTableEvents_ extends TableEvents
{
}
