<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Developer\_generated;

use Atlas\Mapper\MapperSelect;
use LiveryManager\DB\Developer\DeveloperRecord;
use LiveryManager\DB\Developer\DeveloperRecordSet;

/**
 * @method ?DeveloperRecord fetchRecord()
 * @method DeveloperRecord[] fetchRecords()
 * @method DeveloperRecordSet fetchRecordSet()
 * @method ?DeveloperRow fetchRow()
 * @method DeveloperRow[] fetchRows()
 */
abstract class DeveloperSelect_ extends MapperSelect
{
}
