<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Developer\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(50) NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @method \LiveryManager\DB\Developer\DeveloperRow getRow()
 */
abstract class DeveloperRecord_ extends Record
{
}
