<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Developer\_generated;

use Atlas\Mapper\MapperEvents;

abstract class DeveloperEvents_ extends MapperEvents
{
}
