<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Developer\_generated;

use Atlas\Table\TableSelect;
use LiveryManager\DB\Developer\DeveloperRow;

/**
 * @method ?DeveloperRow fetchRow()
 * @method DeveloperRow[] fetchRows()
 */
abstract class DeveloperTableSelect_ extends TableSelect
{
}
