<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Operation\_generated;

use Atlas\Mapper\RecordSet;
use LiveryManager\DB\Operation\OperationRecord;
use LiveryManager\DB\Operation\OperationRecordSet;

/**
 * @method __construct(OperationRecord[], callable $newRecordFactory)
 * @method OperationRecord offsetGet($offset)
 * @method OperationRecord appendNew(array $fields = [])
 * @method ?OperationRecord getOneBy(array $whereEquals)
 * @method OperationRecordSet getAllBy(array $whereEquals)
 * @method ?OperationRecord detachOneBy(array $whereEquals)
 * @method OperationRecordSet detachAllBy(array $whereEquals)
 * @method OperationRecordSet detachAll()
 * @method OperationRecordSet detachDeleted()
 */
abstract class OperationRecordSet_ extends RecordSet
{
}
