<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Operation\_generated;

use Atlas\Table\TableSelect;
use LiveryManager\DB\Operation\OperationRow;

/**
 * @method ?OperationRow fetchRow()
 * @method OperationRow[] fetchRows()
 */
abstract class OperationTableSelect_ extends TableSelect
{
}
