<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Operation\_generated;

use Atlas\Table\Table;
use LiveryManager\DB\Operation\OperationRow;
use LiveryManager\DB\Operation\OperationTableSelect;

/**
 * @method ?OperationRow fetchRow(mixed $primaryVal)
 * @method OperationRow[] fetchRows(array $primaryVals)
 * @method OperationTableSelect select(array $whereEquals = [])
 * @method OperationRow newRow(array $cols = [])
 * @method OperationRow newSelectedRow(array $cols)
 */
abstract class OperationTable_ extends Table
{
    public const DRIVER = 'mysql';

    public const NAME = 'operation';

    public const COLUMNS = [
  'id' => 
  [
    'name' => 'id',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => true,
    'options' => NULL,
  ),
  'name' => 
  [
    'name' => 'name',
    'type' => 'varchar',
    'size' => 50,
    'scale' => NULL,
    'notnull' => true,
    'default' => '',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'created_at' => 
  [
    'name' => 'created_at',
    'type' => 'datetime',
    'size' => NULL,
    'scale' => NULL,
    'notnull' => true,
    'default' => 'current_timestamp()',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
);

    public const COLUMN_NAMES = [
        'id',
        'name',
        'created_at',
    ];

    public const PRIMARY_KEY = [
        'id',
    ];

    public const COMPOSITE_KEY = false;

    public const AUTOINC_COLUMN = null;

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = OperationRow::CLASS;
}
