<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Operation\_generated;

use Atlas\Mapper\MapperSelect;
use LiveryManager\DB\Operation\OperationRecord;
use LiveryManager\DB\Operation\OperationRecordSet;

/**
 * @method ?OperationRecord fetchRecord()
 * @method OperationRecord[] fetchRecords()
 * @method OperationRecordSet fetchRecordSet()
 * @method ?OperationRow fetchRow()
 * @method OperationRow[] fetchRows()
 */
abstract class OperationSelect_ extends MapperSelect
{
}
