<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Operation\_generated;

use Atlas\Mapper\Mapper;
use LiveryManager\DB\Operation\OperationRecord;
use LiveryManager\DB\Operation\OperationRecordSet;
use LiveryManager\DB\Operation\OperationRelated;
use LiveryManager\DB\Operation\OperationSelect;
use LiveryManager\DB\Operation\OperationTable;

/**
 * @method OperationTable getTable()
 * @method ?OperationRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?OperationRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method OperationRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method OperationRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method OperationRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method OperationRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method OperationSelect select(array $whereEquals = [])
 * @method OperationRecord newRecord(array $fields = [])
 * @method OperationRecord[] newRecords(array $fieldSets)
 * @method OperationRecordSet newRecordSet(OperationRecord[] $records = [])
 * @method OperationRecord turnRowIntoRecord(OperationRow $row, array $loadRelated = [])
 * @method OperationRecord[] turnRowsIntoRecords(OperationRow[] $rows, array $loadRelated = [])
 */
abstract class Operation_ extends Mapper
{
    public const RECORD_CLASS = OperationRecord::CLASS;
    public const RECORD_SET_CLASS = OperationRecordSet::CLASS;
    public const RELATED_CLASS = OperationRelated::CLASS;
    public const SELECT_CLASS = OperationSelect::CLASS;
}
