<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery\_generated;

use Atlas\Table\TableSelect;
use LiveryManager\DB\Livery\LiveryRow;

/**
 * @method ?LiveryRow fetchRow()
 * @method LiveryRow[] fetchRows()
 */
abstract class LiveryTableSelect_ extends TableSelect
{
}
