<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery\_generated;

use Atlas\Mapper\MapperSelect;
use LiveryManager\DB\Livery\LiveryRecord;
use LiveryManager\DB\Livery\LiveryRecordSet;

/**
 * @method ?LiveryRecord fetchRecord()
 * @method LiveryRecord[] fetchRecords()
 * @method LiveryRecordSet fetchRecordSet()
 * @method ?LiveryRow fetchRow()
 * @method LiveryRow[] fetchRows()
 */
abstract class LiverySelect_ extends MapperSelect
{
}
