<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery\_generated;

use Atlas\Table\TableEvents;

abstract class LiveryTableEvents_ extends TableEvents
{
}
