<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery\_generated;

use Atlas\Mapper\RecordSet;
use LiveryManager\DB\Livery\LiveryRecord;
use LiveryManager\DB\Livery\LiveryRecordSet;

/**
 * @method __construct(LiveryRecord[], callable $newRecordFactory)
 * @method LiveryRecord offsetGet($offset)
 * @method LiveryRecord appendNew(array $fields = [])
 * @method ?LiveryRecord getOneBy(array $whereEquals)
 * @method LiveryRecordSet getAllBy(array $whereEquals)
 * @method ?LiveryRecord detachOneBy(array $whereEquals)
 * @method LiveryRecordSet detachAllBy(array $whereEquals)
 * @method LiveryRecordSet detachAll()
 * @method LiveryRecordSet detachDeleted()
 */
abstract class LiveryRecordSet_ extends RecordSet
{
}
