<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery\_generated;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(75)
 * @property mixed $tailno varchar(20)
 * @property mixed $storage_path varchar(75) NOT NULL
 * @property mixed $airframe_id int(10,0) unsigned NOT NULL
 * @property mixed $livery_type_id int(10,0) unsigned NOT NULL
 * @property mixed $developer_id int(10,0) unsigned NOT NULL
 * @property mixed $simulator_id int(10,0) unsigned NOT NULL
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 */
abstract class LiveryRow_ extends Row
{
    protected mixed $id = null;
    protected mixed $name = '';
    protected mixed $tailno = '';
    protected mixed $storage_path = '\'/unassigned\'';
    protected mixed $airframe_id = null;
    protected mixed $livery_type_id = null;
    protected mixed $developer_id = null;
    protected mixed $simulator_id = null;
    protected mixed $enabled = 1;
    protected mixed $created_at = 'current_timestamp()';
}
