<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\Livery\_generated;

use Atlas\Table\Table;
use LiveryManager\DB\Livery\LiveryRow;
use LiveryManager\DB\Livery\LiveryTableSelect;

/**
 * @method ?LiveryRow fetchRow(mixed $primaryVal)
 * @method LiveryRow[] fetchRows(array $primaryVals)
 * @method LiveryTableSelect select(array $whereEquals = [])
 * @method LiveryRow newRow(array $cols = [])
 * @method LiveryRow newSelectedRow(array $cols)
 */
abstract class LiveryTable_ extends Table
{
    public const DRIVER = 'mysql';

    public const NAME = 'livery';

    public const COLUMNS = [
  'id' => 
  [
    'name' => 'id',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => true,
    'options' => NULL,
  ),
  'name' => 
  [
    'name' => 'name',
    'type' => 'varchar',
    'size' => 75,
    'scale' => NULL,
    'notnull' => false,
    'default' => '',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'tailno' => 
  [
    'name' => 'tailno',
    'type' => 'varchar',
    'size' => 20,
    'scale' => NULL,
    'notnull' => false,
    'default' => '',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'storage_path' => 
  [
    'name' => 'storage_path',
    'type' => 'varchar',
    'size' => 75,
    'scale' => NULL,
    'notnull' => true,
    'default' => '\'/unassigned\'',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'airframe_id' => 
  [
    'name' => 'airframe_id',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'livery_type_id' => 
  [
    'name' => 'livery_type_id',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'developer_id' => 
  [
    'name' => 'developer_id',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'simulator_id' => 
  [
    'name' => 'simulator_id',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'enabled' => 
  [
    'name' => 'enabled',
    'type' => 'tinyint unsigned',
    'size' => 3,
    'scale' => 0,
    'notnull' => true,
    'default' => 1,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'created_at' => 
  [
    'name' => 'created_at',
    'type' => 'datetime',
    'size' => NULL,
    'scale' => NULL,
    'notnull' => true,
    'default' => 'current_timestamp()',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
);

    public const COLUMN_NAMES = [
        'id',
        'name',
        'tailno',
        'storage_path',
        'airframe_id',
        'livery_type_id',
        'developer_id',
        'simulator_id',
        'enabled',
        'created_at',
    ];

    public const PRIMARY_KEY = [
        'id',
    ];

    public const COMPOSITE_KEY = false;

    public const AUTOINC_COLUMN = null;

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = LiveryRow::CLASS;
}
