<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryVersion\_generated;

use Atlas\Mapper\MapperSelect;
use LiveryManager\DB\LiveryVersion\LiveryVersionRecord;
use LiveryManager\DB\LiveryVersion\LiveryVersionRecordSet;

/**
 * @method ?LiveryVersionRecord fetchRecord()
 * @method LiveryVersionRecord[] fetchRecords()
 * @method LiveryVersionRecordSet fetchRecordSet()
 * @method ?LiveryVersionRow fetchRow()
 * @method LiveryVersionRow[] fetchRows()
 */
abstract class LiveryVersionSelect_ extends MapperSelect
{
}
