<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryVersion\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $version int(10,0) unsigned NOT NULL
 * @property mixed $file_name varchar(100) NOT NULL
 * @property mixed $enabled tinyint(3,0) unsigned NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @method \LiveryManager\DB\LiveryVersion\LiveryVersionRow getRow()
 */
abstract class LiveryVersionRecord_ extends Record
{
}
