<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryVersion\_generated;

use Atlas\Table\Table;
use LiveryManager\DB\LiveryVersion\LiveryVersionRow;
use LiveryManager\DB\LiveryVersion\LiveryVersionTableSelect;

/**
 * @method ?LiveryVersionRow fetchRow(mixed $primaryVal)
 * @method LiveryVersionRow[] fetchRows(array $primaryVals)
 * @method LiveryVersionTableSelect select(array $whereEquals = [])
 * @method LiveryVersionRow newRow(array $cols = [])
 * @method LiveryVersionRow newSelectedRow(array $cols)
 */
abstract class LiveryVersionTable_ extends Table
{
    public const DRIVER = 'mysql';

    public const NAME = 'livery_version';

    public const COLUMNS = [
  'id' => 
  [
    'name' => 'id',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'version' => 
  [
    'name' => 'version',
    'type' => 'int unsigned',
    'size' => 10,
    'scale' => 0,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'file_name' => 
  [
    'name' => 'file_name',
    'type' => 'varchar',
    'size' => 100,
    'scale' => NULL,
    'notnull' => true,
    'default' => '',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'enabled' => 
  [
    'name' => 'enabled',
    'type' => 'tinyint unsigned',
    'size' => 3,
    'scale' => 0,
    'notnull' => true,
    'default' => 1,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
  'created_at' => 
  [
    'name' => 'created_at',
    'type' => 'datetime',
    'size' => NULL,
    'scale' => NULL,
    'notnull' => true,
    'default' => 'current_timestamp()',
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
);

    public const COLUMN_NAMES = [
        'id',
        'version',
        'file_name',
        'enabled',
        'created_at',
    ];

    public const PRIMARY_KEY = [
    ];

    public const COMPOSITE_KEY = false;

    public const AUTOINC_COLUMN = null;

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = LiveryVersionRow::CLASS;
}
