<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryVersion\_generated;

use Atlas\Mapper\RecordSet;
use LiveryManager\DB\LiveryVersion\LiveryVersionRecord;
use LiveryManager\DB\LiveryVersion\LiveryVersionRecordSet;

/**
 * @method __construct(LiveryVersionRecord[], callable $newRecordFactory)
 * @method LiveryVersionRecord offsetGet($offset)
 * @method LiveryVersionRecord appendNew(array $fields = [])
 * @method ?LiveryVersionRecord getOneBy(array $whereEquals)
 * @method LiveryVersionRecordSet getAllBy(array $whereEquals)
 * @method ?LiveryVersionRecord detachOneBy(array $whereEquals)
 * @method LiveryVersionRecordSet detachAllBy(array $whereEquals)
 * @method LiveryVersionRecordSet detachAll()
 * @method LiveryVersionRecordSet detachDeleted()
 */
abstract class LiveryVersionRecordSet_ extends RecordSet
{
}
