<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryVersion\_generated;

use Atlas\Table\TableSelect;
use LiveryManager\DB\LiveryVersion\LiveryVersionRow;

/**
 * @method ?LiveryVersionRow fetchRow()
 * @method LiveryVersionRow[] fetchRows()
 */
abstract class LiveryVersionTableSelect_ extends TableSelect
{
}
