<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryType\_generated;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(50) NOT NULL
 * @property mixed $created_at datetime NOT NULL
 */
abstract class LiveryTypeRow_ extends Row
{
    protected mixed $id = null;
    protected mixed $name = '';
    protected mixed $created_at = 'current_timestamp()';
}
