<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryType\_generated;

use Atlas\Mapper\RecordSet;
use LiveryManager\DB\LiveryType\LiveryTypeRecord;
use LiveryManager\DB\LiveryType\LiveryTypeRecordSet;

/**
 * @method __construct(LiveryTypeRecord[], callable $newRecordFactory)
 * @method LiveryTypeRecord offsetGet($offset)
 * @method LiveryTypeRecord appendNew(array $fields = [])
 * @method ?LiveryTypeRecord getOneBy(array $whereEquals)
 * @method LiveryTypeRecordSet getAllBy(array $whereEquals)
 * @method ?LiveryTypeRecord detachOneBy(array $whereEquals)
 * @method LiveryTypeRecordSet detachAllBy(array $whereEquals)
 * @method LiveryTypeRecordSet detachAll()
 * @method LiveryTypeRecordSet detachDeleted()
 */
abstract class LiveryTypeRecordSet_ extends RecordSet
{
}
