<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryType\_generated;

use Atlas\Table\TableSelect;
use LiveryManager\DB\LiveryType\LiveryTypeRow;

/**
 * @method ?LiveryTypeRow fetchRow()
 * @method LiveryTypeRow[] fetchRows()
 */
abstract class LiveryTypeTableSelect_ extends TableSelect
{
}
