<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryType\_generated;

use Atlas\Mapper\MapperSelect;
use LiveryManager\DB\LiveryType\LiveryTypeRecord;
use LiveryManager\DB\LiveryType\LiveryTypeRecordSet;

/**
 * @method ?LiveryTypeRecord fetchRecord()
 * @method LiveryTypeRecord[] fetchRecords()
 * @method LiveryTypeRecordSet fetchRecordSet()
 * @method ?LiveryTypeRow fetchRow()
 * @method LiveryTypeRow[] fetchRows()
 */
abstract class LiveryTypeSelect_ extends MapperSelect
{
}
