<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace LiveryManager\DB\LiveryVersion;

use Atlas\Table\Table;

/**
 * @method LiveryVersionRow|null fetchRow($primaryVal)
 * @method LiveryVersionRow[] fetchRows(array $primaryVals)
 * @method LiveryVersionTableSelect select(array $whereEquals = [])
 * @method LiveryVersionRow newRow(array $cols = [])
 * @method LiveryVersionRow newSelectedRow(array $cols)
 */
class LiveryVersionTable extends Table
{
    public const DRIVER = 'mysql';

    public const NAME = 'livery_version';

    public const COLUMNS = [
        'id' => array(
  'name' => 'id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => true,
  'primary' => true,
  'options' => null,
),
        'livery_id' => array(
  'name' => 'livery_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'version' => array(
  'name' => 'version',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'changelog' => array(
  'name' => 'changelog',
  'type' => 'mediumtext',
  'size' => 16777215,
  'scale' => null,
  'notnull' => false,
  'default' => 'NULL',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'file_name' => array(
  'name' => 'file_name',
  'type' => 'varchar',
  'size' => 100,
  'scale' => null,
  'notnull' => true,
  'default' => '\'\'',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'enabled' => array(
  'name' => 'enabled',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => 1,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'created_at' => array(
  'name' => 'created_at',
  'type' => 'datetime',
  'size' => null,
  'scale' => null,
  'notnull' => true,
  'default' => 'current_timestamp()',
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
    ];

    public const COLUMN_NAMES = [
        'id',
        'livery_id',
        'version',
        'changelog',
        'file_name',
        'enabled',
        'created_at',
    ];

    public const COLUMN_DEFAULTS = [
        'id' => null,
        'livery_id' => null,
        'version' => null,
        'changelog' => 'NULL',
        'file_name' => '\'\'',
        'enabled' => 1,
        'created_at' => 'current_timestamp()',
    ];

    public const PRIMARY_KEY = [
        'id',
    ];

    public const AUTOINC_COLUMN = 'id';

    public const AUTOINC_SEQUENCE = null;
}
